### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by songy23** [census-instrumentation/opencensus-proto#127]
As we finalized the `metrics` proto (https://github.com/census-instrumentation/opencensus-proto/pull/121) and removed the deprecated `exporter` proto (https://github.com/census-instrumentation/opencensus-proto/pull/124), I think it's a good time to make a new release. A small question would be should this release be another patch release (v0.0.3) or a minor release (v0.1.0)?

I think a minor release makes more sense here since now we can call `metrics` ready-to-use.

/cc @bogdandrutu

**Comment by bogdandrutu** [comment]
Give me few more days.

**Comment by bogdandrutu** [comment]
We also need to add the service definition for metrics.

**Comment by songy23** [comment]
I just realized that it's better to also have the Agent metrics_service.proto ready for the new release, otherwise we'll need to wait for one more release cycle.

**Comment by songy23** [comment]
I believe all release blockers are cleared now. For the new release, I would tag it as v0.1.0 rather than v0.0.3 and start creating release branches, if nobody has objections. I think we've made enough changes to bump to a minor release.
