### ISSUE TITLE
release: make a v0.2.0 release containing the grpc-gateway updates

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-proto#161]
There have been additions of the grpc-gateway in https://github.com/census-instrumentation/opencensus-proto/pull/157 and https://github.com/census-instrumentation/opencensus-proto/pull/156

Could we please make a new release, otherwise currently unable to use this feature so that we can properly use go modules otherwise right now doing say `GO111MODULE=on go get github.com/census-instrumentation/opencensus-proto@master` produces `github.com/census-instrumentation/opencensus-proto@v0.0.3-0.20181214143942-ba49f56771b8` whose git tag is v0.0.3 yet the currently released and highest version is v0.1.0 which then creates a conflict 
```shell
$ GO111MODULE=on go get github.com/census-instrumentation/opencensus-proto@master contrib.go.opencensus.io/exporter/ocagent@master
go: finding github.com/census-instrumentation/opencensus-proto master
go: finding contrib.go.opencensus.io/exporter/ocagent master
go get: inconsistent versions:
	contrib.go.opencensus.io/exporter/ocagent@v0.4.1 from contrib.go.opencensus.io/exporter/ocagent@master requires github.com/census-instrumentation/opencensus-proto@v0.1.0 (not github.com/census-instrumentation/opencensus-proto@v0.0.3-0.20181214143942-ba49f56771b8 from github.com/census-instrumentation/opencensus-proto@master)
```

**Comment by bogdandrutu** [comment]
Is this done?

**Comment by songy23** [comment]
Not yet, waiting on approval of https://github.com/census-instrumentation/opencensus-proto/pull/167.

**Comment by songy23** [comment]
Waiting on https://github.com/census-instrumentation/opencensus-proto/issues/152.

**Comment by odeke-em** [comment]
Hey folks, kindly paging this thread! It has been almost a month.
Could we perhaps make a minor release? This issue is a simple release but holds up tricky go mod dependencies such as for me for the past week
```shell
receiver/opencensus/opencensus.go:232:11: undefined: "github.com/census-instrumentation/opencensus-proto/gen-go/agent/trace/v1".RegisterTraceServiceHandlerFromEndpoint
make: *** [agent] Error 2
```

**Comment by songy23** [comment]
Bumping this up - the version inconsistency in proto has caused troubles in OC-Agent and Agent Exporters. We need to publish a new release to Maven, otherwise the Java Agent exporters won't work with Agent. @odeke-em also saw a bunch of issues from users, where they depend on an outdated proto version in Go exporter and it didn't work with the latest Agent.

@bogdandrutu are there any other blockers for the new release? IMO #152 can roll over to the next release.
