### ISSUE TITLE
The expected use of these protos

### ISSUE THREAD

**Issue by tsloughter** [census-instrumentation/opencensus-proto#168]
Before the `opencensus-service` existed and the grpc service added my understanding was that the protos were simply for defining the types but not for actual use by implementations. The readme seems to still say similar:

> The API interface types are defined using protos to ensure consistency and interoperability for the different implementations.

Now with the service is it right to say that the protos are no longer simply for basing implementations on but are meant to be used for encoding spans and metrics

**Comment by pjanotti** [comment]
I don't have the historical context but having lib exporters focusing on exporting proto brings the points highlighted [here](https://github.com/census-instrumentation/opencensus-service/blob/master/DESIGN.md#architecture-overview).

**Comment by bogdandrutu** [comment]
@tsloughter I think we "re-purpose" these protos. I am happy to review a PR to update the text. Still we use these as the API interface types but also for our lib->agent->collector communication.
