### ISSUE TITLE
Can't tell the difference between unset and zero max_number_of_annotations.

### ISSUE THREAD

**Issue by g-easy** [census-instrumentation/opencensus-proto#179]
https://github.com/census-instrumentation/opencensus-proto/blob/c9cc5de7251f8a320dd6cb4f92e5698ba86f284c/src/opencensus/proto/trace/v1/trace_config.proto#L41

This means that setting a `TraceConfig { constant_sampler { decision: true } }` sets all maximums to zero and produces not very interesting spans as a result.

**Comment by bogdandrutu** [comment]
This is a good point, but I don't think the message is seen as an "update", we should always send the whole config.

**Comment by g-easy** [comment]
Maybe add a comment to the proto definition that all fields must be set?

And/or add explicit defaults into the proto?

**Comment by bogdandrutu** [comment]
@g-easy is the default still a thing in proto3? I think that will be good.

**Comment by g-easy** [comment]
Nope. Explicit default values are not allowed in proto3. :(
