### ISSUE TITLE
Add tracestate to links

### ISSUE THREAD

**Issue by SergeyKanzhelev** [census-instrumentation/opencensus-proto#190]
It would be very useful to have tracestate field to link. So cross-vendor correlation can be achieved easier for links. Sometimes [trace_id and span_id](https://github.com/census-instrumentation/opencensus-proto/blob/e43d650b9d477780880c788ea77ba9d4dbd8d92b/gen-go/trace/v1/trace.pb.go#L807-L811) may not be enough

**Comment by bogdandrutu** [comment]
+1
