### ISSUE TITLE
[Request] Release a jar exposing the proto files

### ISSUE THREAD

**Issue by ericgribkoff** [census-instrumentation/opencensus-proto#31]
Currently [`grpc-java`](https://github.com/grpc/grpc-java) includes a local copy of this repository's [`census.proto`](https://github.com/google/instrumentation-proto/blob/master/stats/census.proto) for use in the gRPC monitoring service. If this proto were available in a released jar, gRPC could avoid maintaining and exposing its own local copy.

**Comment by bogdandrutu** [comment]
One of you can please make the gradle change to allow exporting to maven?
See one example here:
https://github.com/census-instrumentation/opencensus-java/blob/master/build.gradle#L199

**Comment by sebright** [comment]
I don't think that `stats.proto` is ready to be released now.  It hasn't been updated to use the new design (the one used in opencenus-java [stats](https://github.com/census-instrumentation/opencensus-java/tree/master/core/src/main/java/io/opencensus/stats)).

**Comment by bogdandrutu** [comment]
we can remove that from the first release if not ready.

**Comment by sebright** [comment]
census.proto was renamed to stats.proto, so I think we would need to include stats.proto in order for gRPC to use the jar.  Issue #39 covers updating stats.proto.

**Comment by songy23** [comment]
IIRC gRPC monitoring service has already been deprecated so I assume a jar on `stats.proto` is no longer needed at this point. 

We will release jars on all the protos for the Agent work in the future, and those will be tracked in separate issues (e.g https://github.com/census-instrumentation/opencensus-proto/issues/96).
