### ISSUE TITLE
agent/v1: missing ConfigTraceServiceResponse.Node misplaced on ConfigTraceServiceRequest

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-proto#95]
I am currently working on the agent implementation and exporter too and noticed that due to the confusion from the nomenclature of which message is which, we instead have
https://github.com/census-instrumentation/opencensus-proto/blob/3234379e22a61e9df50430f1100cead20d835f11/opencensus/proto/agent/trace/v1/trace_service.proto#L44-L51

and

https://github.com/census-instrumentation/opencensus-proto/blob/3234379e22a61e9df50430f1100cead20d835f11/opencensus/proto/agent/trace/v1/trace_service.proto#L53-L56

which should be the opposite of each other.

This confusion should hopefully be fixed by https://github.com/census-instrumentation/opencensus-proto/pull/93 but now even coming to think of it, the only differentiator there is Node which is populated only once by the client/application. Perhaps we should even just reuse the message for both the agent and applications?

**Comment by songy23** [comment]
My 2 cents: It's definitely possible to use just one message for both Agent and Library, however it will be clearer to distinguish request/response message by name, for example on Library side:
```
config(Stream<UpdatedLibraryConfig> newConfig) {
  // apply config
  CurrentLibraryConfig currentConfig = CurrentLibraryConfig.setNode().setConfig()...;
  // send back
}
```
vs.
```
config(Stream<Config> newConfig) {
  // apply config
  Config currentConfig = Config.setNode().setConfig()...;
  // send back
}
```

**Comment by odeke-em** [comment]
>My 2 cents: It's definitely possible to use just one message for both Agent and Library, however it will be clearer to distinguish request/response message by name, for example on Library side:

True true, plus also if we ever want to update some attribute on either side, have 2 different ones can help a lot so for sure let's keep two different messages.

**Comment by songy23** [comment]
> True true, plus also if we ever want to update some attribute on either side, have 2 different ones can help a lot so for sure let's keep two different messages.

Yep, sounds good.

**Comment by odeke-em** [comment]
Oh btw, FYI this issue wasn't about sharing config messages, it was about the message missing Node https://github.com/census-instrumentation/opencensus-proto/issues/95#issue-357530137
but anyways that's now resolved with https://github.com/census-instrumentation/opencensus-proto/pull/93

**Comment by songy23** [comment]
> it was about the message missing Node #95 (comment)

Yes, the `Node` message is somehow misplaced at first. Should be correct now :)
