### ISSUE TITLE
agent/common/v1: LibraryInfo should disambiguate between library version and exporter version

### ISSUE THREAD

**Issue by odeke-em** [census-instrumentation/opencensus-proto#99]
On review https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/7#discussion_r216053886 @bogdandrutu mentioned that `version` should actually be the library version.

The current field definition suggests that it should be version of the agent exporter. However, we need to propagate information  https://github.com/census-instrumentation/opencensus-proto/blob/ee2e6d8d42906975d77f40b1c73da8c1a58bf405/opencensus/proto/agent/common/v1/common.proto#L85-L86

### Proposal
Instead of the ambiguous `version`, let's instead make 2 fields
* oc_version -- the version of the OpenCensus implementation running
* exporter_version -- the version of the agent exporter running

**Comment by bogdandrutu** [comment]
Don't know if I like the oc_version, maybe lib_version? library_version? or just version? Also because we need to be wire backwards compatible, we should keep id 2 for the exporter and add id 3 for the library.

**Comment by odeke-em** [comment]
`lib*_version`, `version` are too ambiguous IMHO. As you noticed from the PR, as per the proto definitions and despite the comment
https://github.com/census-instrumentation/opencensus-proto/blob/ee2e6d8d42906975d77f40b1c73da8c1a58bf405/opencensus/proto/agent/common/v1/common.proto#L85-L86

 we interpreted things differently about `version`.

For sure, field id 2 should stay as the version of the exporter.

**Comment by bogdandrutu** [comment]
maybe core_library_version? I think if we have 2 fields library_version and exporter_version will not be that confusing.

**Comment by odeke-em** [comment]
Nice, `core_library_version` SGTM, thank you! Now that you mention it, having those 2 fields helps disambiguate it. However, `core_library_version` sets it in stone.

**Comment by songy23** [comment]
`core_library_version ` sounds good to me too.
